name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        name: Install rust toolchain
        with:
          toolchain: nightly
          targets: "i686-pc-windows-msvc"

      - name: Build the installer
        run: cargo build --release
      
      - uses: actions/upload-artifact@v4
        name: Upload Installer
        with:
          name: heffalump_conduit_installer.exe
          path: target/i686-pc-windows-msvc/release/heffalump_conduit_installer.exe

      - name: Clean build artifacts
        run: cargo clean

      - name: Build the conduit dll
        run: cargo build --release --manifest-path conduit/Cargo.toml

      - uses: actions/upload-artifact@v4
        name: Upload Conduit
        with:
          name: heffalump_conduit.dll
          path: conduit/target/i686-pc-windows-msvc/release/heffalump_conduit.dll